name: refresh data, run, test

on:
  push:
    branches:
      - main

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Snowflake Connector
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python[pandas]

      - name: Load Data into Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.DBT_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.DBT_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          # Obtain the CSV files from the URL
          url='https://raw.githubusercontent.com/just4jc/Northwind-Traders-Dataset/main/order_fresh.csv'
          
          # Download CSV file
          wget $url -O order_fresh.csv

          # Put the file into the Snowflake data stage
          python -c "import snowflake.connector; con = snowflake.connector.connect(user='${SNOWFLAKE_USER}', password='${SNOWFLAKE_PASSWORD}', account='${SNOWFLAKE_ACCOUNT}', warehouse='${SNOWFLAKE_WAREHOUSE}', database='${SNOWFLAKE_DATABASE}', schema='${SNOWFLAKE_SCHEMA}'); cur = con.cursor(); cur.execute(\"PUT file://order_fresh.csv @stage;\");"

          # Copy data into Snowflake table
          python -c "import snowflake.connector; con = snowflake.connector.connect(user='${SNOWFLAKE_USER}', password='${SNOWFLAKE_PASSWORD}', account='${SNOWFLAKE_ACCOUNT}', warehouse='${SNOWFLAKE_WAREHOUSE}', database='${SNOWFLAKE_DATABASE}', schema='${SNOWFLAKE_SCHEMA}'); cur = con.cursor(); cur.execute(\"COPY INTO NWTSchema.fresh_orders FROM @stage/order_fresh.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_format') PURGE = FALSE;\");"


          # Obtain the CSV files from the URL
          url='https://raw.githubusercontent.com/just4jc/Northwind-Traders-Dataset/main/order_detail_fresh.csv'
          
          # Download CSV file
          wget $url -O order_detail_fresh.csv

          # Put the file into the Snowflake data stage
          python -c "import snowflake.connector; con = snowflake.connector.connect(user='${SNOWFLAKE_USER}', password='${SNOWFLAKE_PASSWORD}', account='${SNOWFLAKE_ACCOUNT}', warehouse='${SNOWFLAKE_WAREHOUSE}', database='${SNOWFLAKE_DATABASE}', schema='${SNOWFLAKE_SCHEMA}'); cur = con.cursor(); cur.execute(\"PUT file://order_detail_fresh.csv @stage;\");"

          # Copy data into Snowflake table
          python -c "import snowflake.connector; con = snowflake.connector.connect(user='${SNOWFLAKE_USER}', password='${SNOWFLAKE_PASSWORD}', account='${SNOWFLAKE_ACCOUNT}', warehouse='${SNOWFLAKE_WAREHOUSE}', database='${SNOWFLAKE_DATABASE}', schema='${SNOWFLAKE_SCHEMA}'); cur = con.cursor(); cur.execute(\"COPY INTO NWTSchema.fresh_order_detail FROM @stage/order_detail_fresh.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_format') PURGE = FALSE;\");"
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt_snowflake

      - name: Run the fresh_orders (increment fresh orders)
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt run --profiles-dir profiles --models fresh_orders

      - name: Run the fresh_order_detail (increment fresh order detail)
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt run --profiles-dir profiles --models fresh_order_detail
      
      - name: Run the raw_orders (increment new orders)
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt run --profiles-dir profiles --models raw_orders

      - name: Run the raw_order_detail (increment new order detail)
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt run --profiles-dir profiles --models raw_order_detail
        
      - name: run dbt tests
        run: dbt test --profiles-dir profiles
