name: Run dbt test

on:
  push:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    # Steps of the workflow:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt_snowflake

      - name: Run the models
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt run --profiles-dir profiles

      - name: run dbt tests
        run: dbt test --profiles-dir profiles
