name: Run dbt Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt
        run: |
          pip install dbt

      - name: Create dbt_cloud.yml
        run: echo "{}" > /home/runner/.dbt/dbt_cloud.yml

      - name: Run dbt
        run: |
          echo "{}" > /home/runner/.dbt/dbt_cloud.yml
          dbt test --profiles-dir profiles --target dev
