name: Run dbt Pipeline

on:
  push:
    branches:
      - main
      
# Setting some Env variables to work  with profiles.yml
env:
  DBT_PROFILE_TARGET: dev
  DBT_PROFILE_USER: ${{ secrets.DBT_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  dbt_run:
    name: Scheduled dbt refresh and test
    runs-on: ubuntu-latest

    # Steps of the workflow:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Install dbt
        run: pip install dbt

      - name: Run the models
        run: dbt run
        working-directory: ./models/raw/raw_supplier.sql

      - name: Run tests
        run: dbt test
        # working-directory: ./my_dbt_project
